MainApp/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'MainApp'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('pizza', views.pizza, name = 'pizza'),
    path('indiv_pizza/<int:pizza_id>/', views.indiv_pizza, name = 'indiv_pizza'),
]

urlpatterns += staticfiles_urlpatterns()

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
]

MainApp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length = 30)

    def __str__(self):
        return self.pizza_name

class Toppings(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping = models.CharField(max_length = 30)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.topping

MainApp/views.py
from django.shortcuts import render, redirect
from django.template import loader
from .models import Pizza
from .forms import CommentForm


# Create your views here.
def index(request):
    return render(request, 'MainApp/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()
    context = {'pizzas':pizzas}
    return render(request, 'MainApp/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.all()
    context = {'pizza':pizza, "toppings": toppings}
    return render(request, 'MainApp/pizza.html', context)
def new(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else: 
        form = CommentForm()
    context = {'form', form}
    return render(request, 'MainApp/pizza.html', context)






    

    

MainApp/templates/mainapp/base.html
<html>
<body style="background-color:powderblue;"></body>
<p style="font-size: 40"> Davids Pizzaria </p>
<p>
    
    <a  href="{% url 'MainApp:pizza' %}" style="font-size: 30"> Menu 
        
    </a>
    
</p>
{% load static %}
<img src={% static 'pizzaria.jpg' %}
</html>
{% block content %}

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %}

{% block content %}


<p style="font-family: Arial">Welcome to David's Pizzaria! Hot and fresh pizzas availiable for purchase!</p>



{% endblock content %}

MainApp/templates/mainapp/list.html
<body style="background-color:powderblue;"></body>
<ul> 
    {% for x in pizzas %} 
    <a href = "{% url 'MainApp:indiv_pizza/' p.id %}" style="font-size: 20" <li>{{ x }}</li></a>
    {% endfor %}
</ul>



  


  

MainApp/templates/mainapp/pizza.html
{% block content %}

<body style="background-color:powderblue;"></body>

<p> {{ indiv_pizza }} </p>
<ul>
    {% for t in toppings %}
    <li>
        <a href="{% url 'MainApp:pizza' p.id %}" ></a>
         {{ t.text }}
    </li>
    {% empty %}
    <li> There are no Pizzas</li>
    {% endfor %}

</ul>

<h2>Comment</h2>
<form method = 'post'>
    <table>

         {{ form }}

    </table>
    {% crsf_token %}
    <button type = 'submit'>Create</button>
</form>
{% endblock content %}